### PR TITLE
111+ -> 117+

### PR DESCRIPTION
**Pull request by AnBuKu**
Updated number of roles. Needs (since a long time!) as well update of https://pypi.python.org/pypi/debops where the number is still 60+....

### CODE REVIEW

**Review by drybjed — APPROVED** [review]
Maybe we should switch it to `lots` to deal with this once an for all... ;-)

**Comment by AnBuKu** [comment]
Hmmm... Sure, somehow boring on one hand and on the other hand rewarding in terms of "Hey, one role more!"

Or, we do it the same way as DebOps Status page...?

Looking at https://debops.org/status.html I see "There are 118 roles in the DebOps project." The 118 counted by HTML code `<span id="role_count">118</span>` or rather the embedded script (see part of script below), respectively https://api.debops.org/v0/roles/count:debops, automation might work for GitHub and https://pypi.python.org/pypi/debops as well. - Or does `lots` all that?

```
<script>
(function() {
  }
  function update_role_count() {
    var xhr = new XMLHttpRequest();
    xhr.open('get', 'https://api.debops.org/v0/roles/count:debops', true);
    xhr.onload = function() {
      var status = xhr.status;
      if (status == 200) {
        document.getElementById('role_count').innerHTML = xhr.response;
      }
    };
    xhr.send();
  }
</script>

```

**Comment by drybjed** [comment]
I'm not sure if GitHub or PyPI will allow embedded JavaScript in their respective pages.

**Comment by AnBuKu** [comment]
How could we find out? ;-) `</ teasing>`

**Pull request merged**
