### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ghost**
Fix typo and add comma, for clarity

### CODE REVIEW

**Comment by drybjed** [comment]
Thanks, however can you create a PR against the [`debops/debops`](https://github.com/debops/debops/) repository instead? Everything is managed in there now.

**Comment by ghost** [comment]
@drybjed , thanks for your comment, but https://docs.debops.org/en/latest/debops-tools/docs/introduction.html links (at top right of page: "Edit on GitHub") to https://github.com/debops/debops-tools/blob/master/docs/introduction.rst , not to anything under [`debops/debops`](https://github.com/debops/debops) . Is that unintentional?

**Comment by drybjed** [comment]
Actually, I finished migrating the role documentation to the new structure in `debops/debops` yesterday, but I haven't "hooked up" the new documentation at ReadTheDocs yet. I'm currently designing new structure for the documentation, I'm gonna merge it shortly and switch the ReadTheDocs to the monorepo, then it all should be clear. :-)

**Comment by ghost** [comment]
Understood. I'll hold off on docs PRs for now. Thanks for the explanation :)

**Comment by drybjed** [comment]
@sampablokuper OK, the new documentation is up now, at https://docs.debops.org/. It's quite empty for now, so don't be surprised. :-)

**Comment by ghost** [comment]
Closing this in favour of https://github.com/debops/debops/pull/136 . Thanks for the prompt and helpful feedback :)

**Pull request closed without merging**
